-- Seed data for Alexplore Travel Website

-- Insert destinations
INSERT INTO public.destinations (name, slug, description, short_description, image_url, location, rating, review_count, is_featured)
VALUES 
  ('Qaitbay Citadel', 'qaitbay-citadel', 'A 15th-century defensive fortress located on the Mediterranean Sea coast, established in 1477 AD by Sultan Al-Ashraf Sayf al-Din Qa''it Bay. Built on the exact site of the famous Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World.', 'Historic fortress on the Mediterranean coast', '/images/qaitbay-citadel.jpg', 'Eastern Harbor, Alexandria', 4.8, 1250, TRUE),
  ('Montaza Palace', 'montaza-palace', 'Royal palace complex with stunning gardens spanning 150 acres on the Mediterranean coastline. Features beautiful beaches, museums, and the historic Al-Haramlik Palace built during the reign of Khedive Abbas II.', 'Royal palace with Mediterranean gardens', '/images/montaza-palace.jpg', 'Montaza, Alexandria', 4.7, 980, TRUE),
  ('Bibliotheca Alexandrina', 'bibliotheca-alexandrina', 'A major library and cultural center commemorating the ancient Library of Alexandria. This stunning architectural marvel features a distinctive circular design and houses millions of books, museums, and art galleries.', 'Modern library honoring ancient heritage', '/images/bibliotheca.jpg', 'Chatby, Alexandria', 4.9, 2100, TRUE),
  ('Abu al-Abbas al-Mursi Mosque', 'abu-al-abbas-mosque', 'One of the largest and most beautiful mosques in Alexandria, built in honor of the Andalusian Sufi scholar Abu al-Abbas al-Mursi. Features stunning white architecture with intricate Islamic designs.', 'Stunning white Islamic architecture', '/images/mosque.jpg', 'Anfushi, Alexandria', 4.6, 750, TRUE),
  ('Alexandria Corniche', 'alexandria-corniche', 'A waterfront promenade stretching for 20 kilometers along the Mediterranean coast. Perfect for walking, cycling, and enjoying the sea breeze with views of historic buildings and modern cafes.', 'Iconic waterfront promenade', '/images/corniche.jpg', 'Mediterranean Coast, Alexandria', 4.5, 3200, FALSE),
  ('Roman Amphitheater', 'roman-amphitheater', 'The only Roman amphitheater in Egypt, discovered accidentally in 1960. This well-preserved structure features 13 rows of white marble seats and offers insight into Roman entertainment and architecture.', 'Ancient Roman archaeological site', '/images/gallery-1.jpg', 'Kom El Dikka, Alexandria', 4.4, 890, FALSE);

-- Insert packages
INSERT INTO public.packages (name, slug, description, short_description, image_url, duration_days, price_cents, original_price_cents, max_travelers, includes, highlights, rating, review_count, is_featured)
VALUES 
  ('Alexandria Heritage Tour', 'alexandria-heritage-tour', 'Discover the rich history of Alexandria with visits to the Citadel, Library, and Roman ruins. This comprehensive tour covers all major historical sites with expert guides who bring ancient stories to life.', 'Complete historical experience', '/images/hero-alexandria.jpg', 3, 29900, 39900, 15, ARRAY['Hotel accommodation', 'All entrance fees', 'Expert guide', 'Airport transfers', 'Daily breakfast', 'AC transportation'], ARRAY['Visit Qaitbay Citadel', 'Explore Bibliotheca Alexandrina', 'Roman Amphitheater tour', 'Traditional lunch included'], 4.9, 445, TRUE),
  ('Mediterranean Escape', 'mediterranean-escape', 'Relax and rejuvenate with this beachfront getaway package. Stay at a luxury resort, enjoy water activities, and experience the best of Alexandria''s coastal beauty.', 'Beachfront relaxation package', '/images/sunset-sea.jpg', 5, 49900, 64900, 10, ARRAY['5-star hotel', 'Spa treatment', 'Water sports', 'All meals', 'Private beach access', 'Sunset cruise'], ARRAY['Luxury beachfront stay', 'Spa & wellness', 'Snorkeling adventure', 'Sunset yacht cruise'], 4.8, 312, TRUE),
  ('Cultural Immersion Week', 'cultural-immersion-week', 'A deep dive into Alexandrian culture, cuisine, and traditions. Learn to cook Egyptian dishes, visit local markets, and experience authentic daily life in this historic city.', 'Authentic local experiences', '/images/gallery-2.jpg', 7, 79900, 99900, 8, ARRAY['Boutique hotel', 'Cooking classes', 'Market tours', 'All meals', 'Cultural workshops', 'Artisan visits'], ARRAY['Egyptian cooking class', 'Souq exploration', 'Traditional craft workshop', 'Local family dinner'], 4.7, 189, TRUE),
  ('Weekend Getaway', 'weekend-getaway', 'Perfect for a quick escape from Cairo. Visit the highlights of Alexandria in just two days with comfortable accommodation and guided tours.', 'Quick city exploration', '/images/corniche.jpg', 2, 14900, 19900, 20, ARRAY['Hotel accommodation', 'Guided tours', 'Breakfast', 'Transportation'], ARRAY['Citadel visit', 'Library tour', 'Corniche walk', 'Fresh seafood dinner'], 4.6, 678, FALSE),
  ('Luxury Alexandria Experience', 'luxury-alexandria', 'The ultimate premium experience with private guides, 5-star accommodation, fine dining, and exclusive access to special sites. Perfect for discerning travelers.', 'Premium exclusive tour', '/images/hotel-1.jpg', 4, 149900, NULL, 4, ARRAY['5-star suite', 'Private guide', 'Fine dining', 'Luxury transfers', 'VIP access', 'Personal concierge'], ARRAY['Private yacht tour', 'Exclusive palace access', 'Michelin-star dining', 'Personal photographer'], 5.0, 56, TRUE),
  ('Family Adventure', 'family-adventure', 'A fun-filled package designed for families with children. Includes kid-friendly activities, educational tours, and comfortable family accommodation.', 'Fun for all ages', '/images/montaza-palace.jpg', 4, 59900, 74900, 25, ARRAY['Family room', 'Kids activities', 'All meals', 'Guide', 'Transfers', 'Travel insurance'], ARRAY['Interactive museum tours', 'Beach games', 'Camel ride', 'Magic show'], 4.7, 234, FALSE);

-- Insert activities
INSERT INTO public.activities (name, slug, description, short_description, image_url, category, duration_hours, price_cents, rating, review_count, location, is_featured)
VALUES 
  ('Scuba Diving Adventure', 'scuba-diving', 'Explore underwater ruins and marine life in the Mediterranean. Discover ancient artifacts beneath the waves with certified instructors.', 'Underwater exploration', '/images/sunset-sea.jpg', 'water-sports', 4, 8900, 4.8, 156, 'Eastern Harbor', TRUE),
  ('Felucca Sunset Cruise', 'felucca-sunset', 'Traditional sailing experience on a classic Egyptian felucca boat as the sun sets over the Mediterranean.', 'Traditional sailing at sunset', '/images/sunset-sea.jpg', 'water-sports', 2, 3500, 4.9, 423, 'Alexandria Marina', TRUE),
  ('Egyptian Cooking Class', 'cooking-class', 'Learn to prepare authentic Egyptian dishes with a local chef. Market visit included followed by a cooking session and meal.', 'Hands-on culinary experience', '/images/gallery-2.jpg', 'food-dining', 5, 5900, 4.7, 287, 'Downtown Alexandria', TRUE),
  ('Street Food Tour', 'street-food-tour', 'Discover Alexandria''s best street food spots, from koshari to fresh seafood, guided by a local foodie.', 'Local food exploration', '/images/gallery-2.jpg', 'food-dining', 3, 2900, 4.6, 512, 'Various Locations', FALSE),
  ('Library Guided Tour', 'library-tour', 'In-depth exploration of the Bibliotheca Alexandrina with an expert guide covering history, architecture, and collections.', 'Intellectual discovery', '/images/bibliotheca.jpg', 'cultural', 3, 1900, 4.9, 834, 'Bibliotheca Alexandrina', TRUE),
  ('Photography Walking Tour', 'photo-tour', 'Capture the beauty of Alexandria with a professional photographer guide who knows all the best spots and lighting conditions.', 'Visual storytelling', '/images/corniche.jpg', 'cultural', 4, 4500, 4.8, 198, 'Historic Alexandria', FALSE),
  ('Snorkeling Experience', 'snorkeling', 'Easy and fun snorkeling session perfect for beginners. Equipment provided with safety briefing.', 'Marine life discovery', '/images/sunset-sea.jpg', 'water-sports', 2, 2500, 4.5, 324, 'Cleopatra Beach', FALSE),
  ('Historical Walking Tour', 'historical-walking', 'Walk through centuries of history visiting ancient sites, colonial architecture, and hidden gems of old Alexandria.', 'Step back in time', '/images/gallery-1.jpg', 'cultural', 4, 2200, 4.7, 567, 'Historic Center', TRUE);

-- Insert accommodations
INSERT INTO public.accommodations (name, slug, description, short_description, image_url, star_rating, price_per_night_cents, location, amenities, rating, review_count, is_featured)
VALUES 
  ('Four Seasons Hotel Alexandria', 'four-seasons', 'Luxury beachfront resort with world-class amenities, private beach, multiple restaurants, and stunning Mediterranean views. The epitome of sophistication in Alexandria.', 'Ultimate luxury experience', '/images/hotel-1.jpg', 5, 35000, 'San Stefano', ARRAY['Private Beach', 'Spa', 'Pool', 'Fine Dining', 'Gym', 'Concierge', 'Room Service', 'Free WiFi'], 4.9, 1250, TRUE),
  ('Rixos Premium Alexandria', 'rixos-premium', 'Premium all-inclusive resort with excellent facilities, entertainment, and direct beach access. Perfect for families and couples alike.', 'Premium all-inclusive resort', '/images/hotel-2.jpg', 5, 28000, 'Bibliotheca Area', ARRAY['All-Inclusive', 'Beach Access', 'Kids Club', 'Spa', 'Multiple Pools', 'Entertainment', 'Free WiFi'], 4.8, 890, TRUE),
  ('Hilton Alexandria Corniche', 'hilton-corniche', 'Iconic hotel on the famous Corniche with panoramic sea views, excellent restaurants, and easy access to all attractions.', 'Iconic waterfront location', '/images/corniche.jpg', 5, 22000, 'Corniche', ARRAY['Sea View', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Business Center', 'Free WiFi'], 4.7, 2100, FALSE),
  ('Steigenberger Cecil Hotel', 'steigenberger-cecil', 'Historic luxury hotel dating back to 1929, combining old-world charm with modern amenities. A landmark of Alexandria.', 'Historic elegance', '/images/hero-alexandria.jpg', 4, 15000, 'Raml Station', ARRAY['Historic Building', 'Restaurant', 'Bar', 'Room Service', 'Concierge', 'Free WiFi'], 4.6, 780, TRUE),
  ('Paradise Inn Windsor Palace', 'windsor-palace', 'Charming boutique hotel in a historic building with Mediterranean architecture and personalized service.', 'Boutique Mediterranean charm', '/images/montaza-palace.jpg', 4, 12000, 'El Shatby', ARRAY['Sea View', 'Restaurant', 'Garden', 'Free Parking', 'Free WiFi'], 4.5, 456, FALSE),
  ('Tolip Hotel Alexandria', 'tolip-hotel', 'Modern business hotel with excellent facilities, convenient location, and professional service.', 'Modern comfort', '/images/hotel-1.jpg', 4, 9500, 'Smouha', ARRAY['Pool', 'Gym', 'Restaurant', 'Business Center', 'Free Parking', 'Free WiFi'], 4.4, 567, FALSE);
